config/routes.rb
Rails.application.routes.draw do
root 'posts#index', as: 'home'

get 'about' => 'pages#about', as: 'about'

resources :posts do
	resources :comments 
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord
	has_many :comments
	validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
		# Если добавить строчку ниже и добавить в исключение метод create тогда комменты будут добавляться только если чел знает пароль
		# http_basic_authenticate_with name: "admin", password: "admin123", except: [:index, :show]
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)

		redirect_to post_path(@post)
	end

	private def comment_params
		params.require(:comment).permit(:username, :body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about 
		@heading = 'Страница компании рога и копыта)))!!!'
		@textInfo = 'Какой то просто текст!!'
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	http_basic_authenticate_with name: "admin", password: "admin123", except: [:index, :show]

def index
	@post = Post.all
end

def new
	@post = Post.new
end

def show
	@post = Post.find(params[:id])
end

def edit
	@post = Post.find(params[:id])
end

def update
	@post = Post.find(params[:id])

	if(@post.update(post_params))
		redirect_to @post
	else
		render 'edit'
	end
end

def destroy
	Post.find(params[:id])

	post.destroy

	redirect_to posts_path
end

def create
	# render plain: params[:post].inspect
	@post = Post.new(post_params)

	if(@post.save)
		redirect_to @post
	else
		render 'new'
	end
end

private def post_params 
	params.require(:post).paramit(:title, :body)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
	
	    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal">Test site</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <span class="p-2 text-dark" ><% link_to "Главная страница", home_path %></span>
        <span class="p-2 text-dark" ><% link_to "О компании", about_path %></span>
        <span class="p-2 text-dark" ><% link_to "Добавление записи", new_post_path %></span>
      </nav>
      <a class="btn btn-outline-primary" href="#">Sign up</a>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @heading %></h1>
<p>
	<%= @textInfo %>
</p>

app/views/posts/edit.html.erb
<h2>Редактирование записи!</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><% msg %></div>
		<% end %>
	<% end %>
<p>
	Название записи <br/>
	<%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
	Текст записи <br/>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p><%= f.submit({:class => 'btn btn-md btn-success'}) %></p>

<% end %>

app/views/posts/index.html.erb
<h1>Главная страница</h1>
<h2>Все наши новости (записи)</h2>

<% @post.each do |post| %>
	<div class="well">
		<h3><%= post.title %></h3>
		<p><%= post.body %></p>
		<% link_to "Смотреть подробно", posts_path(post), :class => 'btn btn-sm btn-primary' %>
	</div>
<% end %>

app/views/posts/new.html.erb
<h2>Добавление нового поста!</h2>
<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><% msg %></div>
		<% end %>
	<% end %>
<p>
	Название записи <br/>
	<%= f.text_field(:title, {:class => 'form-control'}) %>
</p>

<p>
	Текст записи <br/>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p><%= f.submit({:class => 'btn btn-md btn-success'}) %></p>

<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<% link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-sm btn-warning' %>
<% link_to "Удалить", post_path(@post), method: :delete, data: {confirm: "Хотите удалить запись?"}, :class => 'btn btn-sm btn-danger' %>
<hr>
<h2>Все Комментарии</h2>

<% @post.comments.each do |comment| %>
	<div class="alert alert-light">
		<p><strong><% comment.username %></strong> : <% comment.body %></p>
	</div>
<% end %>


<hr>
<h2>Добавление нового Комментария!</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
<p>
	Пользователь <br/>
	<%= f.text_field(:username, {:class => 'form-control'}) %>
</p>

<p>
	Текст комментария <br/>
	<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>

<p><%= f.submit("Добавить комментарий", {:class => 'btn btn-md btn-warning'}) %></p>

<% end %>